[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist/"
  function = "functions"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"


[dev]
  framework = "#custom"
  command = "npm run serve:webpack"
  targetPort = 8080
  autoLaunch = true